# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='idnum',
        ),
    ]
