# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_device_idnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
                ('Info', models.CharField(max_length=1000)),
                ('Photo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('humidity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='device',
            name='temp',
        ),
        migrations.AddField(
            model_name='device',
            name='place',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.City'),
        ),
        migrations.AddField(
            model_name='info',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Device'),
        ),
    ]
