# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 23:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 23, 26, 50, 250857, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
