# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_info_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
