# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190404_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='lat',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='lon',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
    ]
