# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-04 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190404_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
