# Generated by Django 2.0 on 2019-04-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190404_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='Info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='Photo',
            new_name='photo',
        ),
    ]
