# Generated by Django 2.0 on 2019-04-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190404_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='info',
            new_name='Info',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='photo',
            new_name='Photo',
        ),
    ]
